# Generated by Django 6.0.7 on 2026-07-24 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests', to='accounts.shop')),
            ],
            options={
                'db_table': 'stock_requests',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In transit'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_DISCREPANCY', 'Completed with discrepancy')], default='PENDING', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('destination_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='accounts.shop')),
                ('request', models.ForeignKey(blank=True, help_text='NULL when created directly by management (BR-TRF-001)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockops.stockrequest')),
                ('source_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='accounts.shop')),
            ],
            options={
                'db_table': 'transfers',
            },
        ),
        migrations.CreateModel(
            name='TransferDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('MATCHED', 'Matched'), ('DISCREPANCY', 'Discrepancy')], default='PENDING', max_length=12)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockitem')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='stockops.transfer')),
            ],
            options={
                'db_table': 'transfer_details',
            },
        ),
    ]
