# Generated by Django 6.0.7 on 2026-07-25 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('stockops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferBulkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipped_quantity', models.PositiveIntegerField()),
                ('received_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('MATCHED', 'Matched'), ('DISCREPANCY', 'Discrepancy')], default='PENDING', max_length=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_details', to='stockops.transfer')),
            ],
            options={
                'db_table': 'transfer_bulk_details',
            },
        ),
    ]
