# Generated by Django 6.0.7 on 2026-07-24 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('identifier_type', models.CharField(choices=[('IMEI', 'IMEI'), ('SERIAL', 'Serial'), ('NONE', 'None')], default='NONE', max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('ASSIGNED', 'Assigned'), ('SOLD', 'Sold'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], default='AVAILABLE', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='catalog.product')),
            ],
            options={
                'db_table': 'stock_items',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RECEPTION', 'Reception'), ('SALE', 'Sale'), ('TRANSFER', 'Transfer'), ('ASSIGNMENT', 'Assignment'), ('ADJUSTMENT', 'Adjustment')], max_length=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockitem')),
            ],
            options={
                'db_table': 'stock_movements',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('minimum_level', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='catalog.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='accounts.shop')),
            ],
            options={
                'db_table': 'inventories',
                'unique_together': {('shop', 'product')},
            },
        ),
    ]
